### ISSUE TITLE
File paths/metadata

### ISSUE THREAD

**Issue by chriszs** [PublicI/fcc-files-loader#1]
How do we want to organize this to retain metadata?  Do we want to place files at`AM/KSIR/Political Files/2018/federal/US House/Buck for Colo KSIR Nov 2018.pdf`? Or would it make more sense to burn in metadata into the PDF in some other arrangement? What else should be burned in? Station location? How's does that work for cable systems? Experiment with this in Backlight.

**Comment by pratheekrebala** [comment]
For political entities, it would be helpful to have FEC Ids in the path somewhere.

**Comment by chriszs** [comment]
Uploaded some test documents with no file path, human-readable file name or metadata and that it did this automatically is already really cool:
![Screen Shot 2020-02-18 at 3 05 22 PM](https://user-images.githubusercontent.com/1103467/74773861-b2e65900-5260-11ea-88fc-13032af2816c.png)

**Comment by chriszs** [comment]
One issue: Backlight seems to ignore directory paths. Can't tell if it processes metadata or not.

**Comment by chriszs** [comment]
Asked Google about metadata. Might just name files like `AM-KSIR-2018-federal-US House-Buck for Colo KSIR Nov 2018.pdf`.

**Comment by pratheekrebala** [comment]
Good call! Also, flagging type of document - RECEIPT/INVOICE might be helpful. I'm guessing there'll be a ton of duplicate orders etc here.

**Comment by pratheekrebala** [comment]
Does Backlight not have a place to throw in some kind of JSON metadata?

**Comment by chriszs** [comment]
Unclear. The way you get files in as a consumer is by uploading to Google Drive, which is how I'm testing. Could possibly see if Drive metadata makes a difference, but my guess is no.

**Comment by chriszs** [comment]
That's why I'm asking Google.

**Comment by chriszs** [comment]
Currently looks like:
```
TX - LAREDO - TV - KGNS - 2020 - Federal - President - Bernie Sanders - Review Form BS-TX 101H.pdf
CO - CASTLE ROCK - FM - KJMN - 2019 - Non-Candidate Issue Ads - Q4 2019 - 493525-2 Hispanic Chamber of commerce KJMN.pdf
```

Just shoot me.
